theme: jekyll-theme-minimal
title: Muskan's homepage
description: Bookmark this to keep an eye on my project updates!
title: Muskan.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
